### ISSUE TITLE
Problem with concepts-by-TMP

### ISSUE THREAD

**Issue by noirgif** [ustc-compiler-concepts/report#2]
There's a line in the document:

```cpp
using Arithmetic = typename std::enable_if<_Arithmetic<T>::value>::type;
```
It gives `void` if `_Arithmetic<T>::value` is `true`, rather than `T`.

See [the document](http://en.cppreference.com/w/cpp/types/enable_if).

**Comment by gloit042** [comment]
`Arithmetic` here is used for type construction check. It doesn't matter what type it generates.
