### ISSUE TITLE
Example type-class-in-haskell not working

### ISSUE THREAD

**Issue by noirgif** [ustc-compiler-concepts/report#3]
There are some problems with the C++ code it provides:
1. `element` undefined in `requires Hashable<element>;`
2. Trying to call a member function of a typename in `X.size()`.
3. Missing semicolon**s** at the end of the concept and class definition.
4. The code:

```cpp
template<Hashable K>
struct intmap<list<K>> {/*blablabla*/};
```

is invalid. If you need a list as the template, try declaring it like:

```cpp
template<Hashable K, template<typename...> L>
struct intmap;
```

Then specify the requirements.

To round it up: please provide a minimal working example rather than a piece of c++-like pseudocode.

**Comment by gloit042** [comment]
1. fixed by replacing `element` with `X::element`
2. fixed by adding parameterized constraint
3. added
4. fixed by providing a declaration
